### ISSUE TITLE
Error when changing to fluent

### ISSUE THREAD

**Issue by najdias** [laravel-doctrine/fluent#28]
As soon as I change my metadata at doctrine config to fluent i get this error when run `php artisan doctrine:migrations:diff` :

`[Doctrine\Common\Annotations\AnnotationException]
  [Semantical Error] The annotation "@Doctrine\ORM\Mapping\MappedSuperclass"
  in class Gedmo\Translatable\Entity\MappedSuperclass\AbstractPersonalTransla
  tion does not exist, or could not be auto-loaded.`

**Comment by patrickbrouwers** [comment]
Currently Fluent with Gedmo extensions is not supported yet, we are working on it.
You will have to add both Fluent and annotations driver to the mapping driver chain.

**Comment by byfoz** [comment]
I'm not sure if this is going to be any help or not, but I've spent a fair bit today trying to get my head around Fluent / Gedmo Extensions.

### Fixing the error above

To get GedmoExtensions working in a 'hybrid' mode while we wait for Fluent to support them, you can do the following:
1. Create your own custom service provider (or alternatively edit the existing one - though not recommended). I placed my one in App\Providers\DoctrineServiceProvider.php, and register this in your config/app.php file.
2. Add the following to the boot() method:

```
AnnotationRegistry::registerFile(base_path('vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/DoctrineAnnotations.php');
```

This loads the annotations needed to prevent the error 

> [Doctrine\Common\Annotations\AnnotationException] [Semantical Error] The annotation "@Doctrine\ORM\Mapping\MappedSuperclass" in class Gedmo\Translatable\Entity\MappedSuperclass\AbstractPersonalTranslation does not exist, or could not be auto-loaded.

### Using the extensions

To get Timestampable working, I then imported 'TimestampableEntity' trait from Gedmo into my Entity, and in the normal Fluent Mapping file for that entity, add the following:

```
$builder->timestamp('createdAt');
$builder->timestamp('updatedAt');
```

To get Soft Deletes working, I did a similar thing by importing 'SoftDeleteableEntity'. Make sure to add the following to your mapping:

```
$builder->timestamp('deletedAt');
```

Unfortunately Gedmo still expects you to tell it which classes are 'SoftDeleteable' - so you have to place this at the top of any entities you want to use soft deletes on:

```
use Gedmo\Mapping\Annotation as Gedmo;
/**
 * @Gedmo\SoftDeleteable(fieldName="deletedAt", timeAware=false)
 */
class MyEntity  {
...
```

--- this is all a bit hacky but hopefully just a temporary fix until they are fully supported.

**Comment by patrickbrouwers** [comment]
We are currently working on fully supporting Gedmo extensions. Hope to have it finished this weekend.

Will be as simple as

``` php
$builder->timestamps();
$builder->dateTime('createdAt')->timestampable()->onCreate();
```

**Comment by byfoz** [comment]
@patrickbrouwers Excellent, thanks for the update. Look forward to seeing how it will be implemented :)

**Comment by najdias** [comment]
@CImrie Thanks for the fix but maybe I will wait to be fully supported as @patrickbrouwers said.
Thank you both.

**Comment by oddz** [comment]
Extensions now seem to be at least partially working. Using the extensions-support branch I was able to use Tree by placing the following line(s) in the register method of my own provider.

`		$chain = new MappingDriverChain();
		GedmoExtensions::registerAll($chain);`

**Comment by oddz** [comment]
Actually never mind there was trickery involved with the config to hook it all up.

**Comment by patrickbrouwers** [comment]
With the version 1.1 release, Fluent officially supports gedmo extensions. Please let us know your experience :)
