### ISSUE TITLE
Sluggable in Fluent

### ISSUE THREAD

**Issue by jhaoda** [laravel-doctrine/fluent#33]
laravel-doctrine/fluent v1.1.1

``` php
// ProductMapping.php

// ...
$builder->string('slug')->sluggable(['title', 'code']);
// ...
```

Run `php artisan doctrine:migration:diff`, got error `No mapping found for field 'slug' on class 'App\Domain\Product'`.

But error gone after commenting https://github.com/laravel-doctrine/fluent/blob/1.1/src/Extensions/Gedmo/Sluggable.php#L98.

**Comment by guiwoda** [comment]
This should go away if the `Sluggable` field builder is delayed, as it depends on fields being built before it.

**Comment by jhaoda** [comment]
@guiwoda how make this builder delayed?

**Comment by guiwoda** [comment]
@jhaoda it's not something you can do on userland. The `LaravelDoctrine\Fluent\Extensions\Gedmo\Sluggable` class should implement the `LaravelDoctrine\Fluent\Builders\Delay` marker interface.

I'll see if I can push the fix later today.

**Comment by guiwoda** [comment]
I was wrong about needing to `Delay` it, it only needed to validate on build instead of validating on construction.

@patrickbrouwers do you mind if we merge #34?

**Comment by jhaoda** [comment]
@guiwoda thanks!
