### ISSUE TITLE
Class Table  Inheritance

### ISSUE THREAD

**Issue by greabock** [laravel-doctrine/fluent#36]
Hi! What about [Class Table  Inheritance](http://doctrine-orm.readthedocs.io/projects/doctrine-orm/en/latest/reference/inheritance-mapping.html#class-table-inheritance) implementation for fluent mapping?

**Comment by greabock** [comment]
Ah sorry, it's my inattention. "Joined" is. But it realy confusing me - why different naming?

**Comment by patrickbrouwers** [comment]
I don't really understand what's confusing about the naming? It's called exactly what it is: table inheritance. Both joined and single are present.

Did you check the docs? http://www.laraveldoctrine.org/docs/1.1/fluent/reference#inheritance

```
$builder->singleTableInheritance()->column('type');
$builder->joinedTableInheritance()->column('type');
$builder->inheritance('JOINED');
$builder->inheritance(LaravelDoctrine\Fluent\Builders\Inheritance\Inheritance::JOINED);

$builder->singleTableInheritance(function (Inheritance $inheritance) {
            $inheritance->column('imageable_type', 'string');
            $inheritance->map('product', ProductImage::class);
            $inheritance->map('page', PageImage::class);
});
```

**Comment by greabock** [comment]
It's not about code. It's about documentation. In official doctrine documentation this section entitled as "Class Table Inheritance", but in fluent documentation same section entitled as "Joined table inheritance". It confused me a little.

**Comment by patrickbrouwers** [comment]
The title of the section actually is Inheritance mapping. Feel free to PR changes that would clarify it for you.
