### ISSUE TITLE
$builder->string('name')->index(); returns an error

### ISSUE THREAD

**Issue by glennjacobs** [laravel-doctrine/fluent#43]
I set up a simple mapping and when I added an index using the example below I get... 

    [BadMethodCallException]                     
    FieldBuilder method [index] does not exist.

Example

    public function map(Fluent $builder)
    {
        $builder->increments('id');
        $builder->string('name');
        $builder->string('type')->index();
        $builder->timestamps();
    }

However, this works

    public function map(Fluent $builder)
    {
        $builder->increments('id');
        $builder->string('name');
        $builder->string('type');
        $builder->timestamps();

        $builder->index('type');
    }

**Comment by guiwoda** [comment]
That is true, indeed. Seems we had that planned and documented, but never got to implement it.

Being a shortcut, I won't make it a top priority. But if you can spare some time on an implementation, a PR would be more than welcomed!

**Comment by glennjacobs** [comment]
That'll explain it then :)

I'll try...

**Comment by patrickbrouwers** [comment]
Feature is added in latest release
