### ISSUE TITLE
findOneBy() and findBy() not working with embedded fields 

### ISSUE THREAD

**Issue by catalinbuletin** [laravel-doctrine/fluent#51]
This is part of my UserMapping
```
public function map(Fluent $builder)
    {
        $builder->increments('id');
        $builder->embed(FirstName::class)->noPrefix();
        $builder->embed(LastName::class)->noPrefix();
        $builder->embed(Email::class)->noPrefix();
    }
```

When I try to:
```
        $users = $this->userRepository->findOneBy([
            'email' => 'email@example.com'
        ]);
```
I get this:
`Doctrine \ ORM \ ORMException
Unrecognized field: email`

But if I change the UserMapping to use a string instead of the embedded field
```
public function map(Fluent $builder)
    {
        $builder->increments('id');
        $builder->embed(FirstName::class)->noPrefix();
        $builder->embed(LastName::class)->noPrefix();
        $builder->string('email');
    }
```
This will work as expected.

Any thoughts of why i get `Unrecognized field: email` when the field is a ValueObject?

Thank you!

**Comment by patrickbrouwers** [comment]
This is not really a specific Fluent problem. This is how Doctrine embedded fields work.

You need to query on the embedded name and the field within that embedded. 
E.g.:
```
 $users = $this->userRepository->findOneBy([
            'email.address' => 'email@example.com'
        ]);
```

See for example: https://stackoverflow.com/questions/30321224/doctrine-orm-querying-by-value-object-throws-a-semantic-error-mappings-for-inse

**Comment by catalinbuletin** [comment]
You are right! Thanks for your input and for the package as well! Keep it up!

**Comment by floriankraemer** [comment]
@patrickbrouwers this information should be added to the documentation (https://www.doctrine-project.org/projects/doctrine-orm/en/3.3/tutorials/embeddables.html#initializing-embeddables), its not mentioned here. I was searching for it and ended up here.
