### ISSUE TITLE
Add a boot method to the Mappings

### ISSUE THREAD

**Issue by ing200086** [laravel-doctrine/fluent#54]
To make it so you do not need to update and change doctrine.php it would be nice to have the mapping class boot and add itself.

**Comment by guiwoda** [comment]
Check #48 and #49, those PRs cover what you´re asking for (finding mapping files automatically for given path(s).)

**Comment by ing200086** [comment]
It looks like you guys haven't decided on the method of application between those two. Can something be added to the documentation to describe your chosen method?

**Comment by guiwoda** [comment]
Docs will be upgraded once the feature hits master, in the meantime, you can implement it on your project with any kind of file finder, just as the PRs do. If you have any feedback on either of the methods, feel free to chip in the PRs with your thoughts!
