### ISSUE TITLE
Cannot use enum column type

### ISSUE THREAD

**Issue by catalinbuletin** [laravel-doctrine/fluent#55]
Hello,

I can't seem to be able to use the `enum` type.

in my config, i have uncommented this line:

            'mapping_types' => [
                'enum' => 'string'
            ]

And in the mapping I use it like this:
`$builder->field('enum', 'someField');`

Do I need to do something else to make it work?

Thanks a lot!

**Comment by patrickbrouwers** [comment]
Can you specify what you mean with "can't seem to be able to use". Do you get errors?

**Comment by catalinbuletin** [comment]
Hey! I can't remember what that issue was. It's 3 months old. It's working now, so i'll close this issue

**Comment by patrickbrouwers** [comment]
Great 👍
