### ISSUE TITLE
How to escape reserved words with Fluent mappping?

### ISSUE THREAD

**Issue by Stolz** [laravel-doctrine/fluent#60]
My `Notification` entity has a field named `level`. I'm using Oracle Database where `level` is a reserved keyword so for every SQL than involves notification the `level` field needs to be escaped to `"LEVEL"` otherwise Oracle will throw an error

> ORA-01747: invalid user.table.column, table.column, or column specification

I know [Doctrine does not quote identifiers automatically and quoting column names needs to be done explicitly using ticks in the definition](https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/basic-mapping.html#quoting-reserved-words).

The problem is I don't know who to achieve the `ticks` feature when using `LaravelDoctrine\Fluent\Fluent`. If I try adding the ticks ...

```php
    public function map(Fluent $builder)
    {
        $builder->increments('id');
        $builder->string('`level`');
        // ... redacted for brevity
    }
```
... then I always get the error

> Property App\Models\Notification::$\`level\` does not exist

So, how do I specify in `FluentMapping` that `level` column should be escaped?

**Comment by dpgover** [comment]
Have you tried something like this? 
`$builder->string('level')->columnName('`level`');`

**Comment by Stolz** [comment]
Thanks @dpgover. It worked!. Using `columnName` with ticks and setting the column name in upper case did the trick

    $builder->string('level')->columnName('`LEVEL`');
