### ISSUE TITLE
Using unique causes a specified key too long exception

### ISSUE THREAD

**Issue by peppermintology** [laravel-doctrine/fluent#61]
When I add the `unique` constraint to my string field and run my migration, I get a `SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes", Object(Doctrine\DBAL\Driver\PDOException))` exception.

`$builder->string('email')->unique();`

Without `unique()` the migration executes fine.

I have added `Schema::defaultStringLength(191);` to my `AppServiceProvider.php` file as per the Laravel documentation, but this does not appear to have resolved the issue.

I'm using:
- Laravel 5.6
- MariaDB 15.1
- PHP 7.2

**Comment by peppermintology** [comment]
This appears to be more my misunderstanding of how the `Doctrine ORM/Fluent` packages and `Laravel` work. Setting the length on the field fixed it.

`$builder->string('email')->length(191)->unique();`

**Comment by patrickbrouwers** [comment]
Schema::defaultStringLength(191); is not related to this package no.
