### ISSUE TITLE
Does this package depend on laravel framework or its components? 

### ISSUE THREAD

**Issue by HallofFamer** [laravel-doctrine/fluent#67]
Hello there, I am amazed to find this library as I've always been looking for a fluent API similar to C#'s entity framework fluent API. To me this is by far the most optimal solution for data mapping, as I do not like either annotations(violating separation of concerns) or XML(the notorious XML hell). Thank you so much for making this library, its an eye opener and can work in production environment. 

I wonder though, is there a reason why the top namespace is LaravelDoctrine? I looked at the composer.json and did not find any dependency on Laravel framework and its core libraries. Does this mean that, the library can be used with or without Laravel framework? I thought the package LaravelDoctrine is supposed to be used for Laravel's implementation of Doctrine only, correct me if I am wrong.

**Comment by patrickbrouwers** [comment]
Hey @HallofFamer the package was an initiative from the developers who already worked on Laravel Doctrine and is also heavily inspired on Laravel's syntax for migrations. However there's no dependency on Laravel, it works with any project that uses Doctrine.
