### ISSUE TITLE
FluentDriver use error with Laravel 8

### ISSUE THREAD

**Issue by MasterTheRock** [laravel-doctrine/fluent#69]
I try to use laravel-doctrine/fluent 1.1.7 with Laravel 8, but in the file **FluentDriver.php** there have some **use** error for: 
- Doctrine\Common\Persistence\Mapping\ClassMetadata 
- Doctrine\Common\Persistence\Mapping\Driver\MappingDriver
I need to remove **Common** in the **use** for everything work.

**Comment by eigan** [comment]
Should be fixed in 1.2.0. Please try it out :)

**Comment by MasterTheRock** [comment]
Nice! is working. Thanks!

**Comment by FoxxMD** [comment]
I'm not sure how but I believe this broke (at least) Gedmo extensions for me..
* laravel-doctrine/orm @ 1.4.18
* laravel-doctrine/1.1.7 => 1.2.0
* laravel-doctrine/extensions 1.0.14
* doctrine/orm @ 2.6.6

None of the gedmo extensions are acting on entities anymore (blameable is what I caught). Only change in composer.lock was fluent form 1.1.7 => 1.2.0
