### ISSUE TITLE
doctrine/orm version bump

### ISSUE THREAD

**Issue by dpgover** [laravel-doctrine/fluent#75]
@eigan For this package to work with Laravel 9, doctrine/inflector needs to be used in version 2.0 at least.
Version 1.4 changed the API and the old one is deprecated.

I left a PR for this: #74 

Also, this package is requiring multiple doctrine/orm versions, while laravel-doctrine/orm is only requiring ^2.6.
Do you think we can change the requirements on composer.json to be alligned?

**Comment by eigan** [comment]
Thanks @dpgover! Looks good.

Change to ^2.6 is a good idea.

Could you update https://github.com/laravel-doctrine/fluent/blob/1.x/.github/workflows/ci.yml too? Add 2.10 and 2.11 :)

**Comment by dpgover** [comment]
I have the chages in another branch on my fork. I'll make another PR for that then.
Have in mind that the change requires dbal 2.12.x or 3.x.

**Comment by dpgover** [comment]
Done.

@eigan see #76 with the changes for doctrine/inflector and doctrine/orm.

We are trying to upgrade to Laravel 9, so a new release will be really appreciated :)

**Comment by eigan** [comment]
Sorry for the delay. Was on vacation. Will release this soon (within 24 hours)

**Comment by eigan** [comment]
Released now as 1.3, thanks!

**Comment by dpgover** [comment]
🔥 🚀 🎉
